# project informations for Bukkit in order to register our plugin with all it components
# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

# meta informations for plugin managers
authors: [games647, 'https://github.com/games647/TabChannels/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}
api-version: 1.13

# Load after Protcollib for registering the packet listener
sofdepend: [ProtocolLib]

commands:
    switchchannel:
        description: 'Switches the chat channel'
        aliases: [switch, channel]
        permission: ${project.artifactId}.command.switch

    private:
        description: 'Creates a private chat channel with your partner'
        aliases: [tell, pm]
        permission: ${project.artifactId}.command.private

    ${project.artifactId}:
        description: 'All relevant commands to interact with chat channels'
        aliases: [channel, tb]

    createchannel:
        description: 'Creates'
        aliases: ['${project.artifactId}:create']
        permission: ${project.artifactId}.command.create